/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: fd840e184902fd3e746ad643e3eaaa27)
declare namespace Cloudflare {
	interface Env {
		DEVMODE: string;
		JWT_SECRET: string;
		SyncObject: DurableObjectNamespace<import("./src/index").SyncObject>;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
